/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as PayCodeRouteImport } from './routes/pay.$code'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing-webhook'
import { Route as AuthenticatedDashboardVideosRouteImport } from './routes/_authenticated/dashboard.videos'
import { Route as AuthenticatedDashboardUgcRouteImport } from './routes/_authenticated/dashboard.ugc'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard.transactions'
import { Route as AuthenticatedDashboardStorefrontRouteImport } from './routes/_authenticated/dashboard.storefront'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardProductsRouteImport } from './routes/_authenticated/dashboard.products'
import { Route as AuthenticatedDashboardPostsRouteImport } from './routes/_authenticated/dashboard.posts'
import { Route as AuthenticatedDashboardPayoutsRouteImport } from './routes/_authenticated/dashboard.payouts'
import { Route as AuthenticatedDashboardPaymentLinksRouteImport } from './routes/_authenticated/dashboard.payment-links'
import { Route as AuthenticatedDashboardNewRouteImport } from './routes/_authenticated/dashboard.new'
import { Route as AuthenticatedDashboardImagesRouteImport } from './routes/_authenticated/dashboard.images'
import { Route as AuthenticatedDashboardEmailsRouteImport } from './routes/_authenticated/dashboard.emails'
import { Route as AuthenticatedDashboardEmailRouteImport } from './routes/_authenticated/dashboard.email'
import { Route as AuthenticatedDashboardEarningsRouteImport } from './routes/_authenticated/dashboard.earnings'
import { Route as AuthenticatedDashboardContentRouteImport } from './routes/_authenticated/dashboard.content'
import { Route as AuthenticatedDashboardContactsRouteImport } from './routes/_authenticated/dashboard.contacts'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardAutomationsRouteImport } from './routes/_authenticated/dashboard.automations'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardAdsRouteImport } from './routes/_authenticated/dashboard.ads'
import { Route as AuthenticatedDashboardProductsIndexRouteImport } from './routes/_authenticated/dashboard.products.index'
import { Route as AuthenticatedDashboardContentIndexRouteImport } from './routes/_authenticated/dashboard.content.index'
import { Route as AuthenticatedDashboardAdsIndexRouteImport } from './routes/_authenticated/dashboard.ads.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedDashboardVideosBusinessIdRouteImport } from './routes/_authenticated/dashboard.videos.$businessId'
import { Route as AuthenticatedDashboardUgcBusinessIdRouteImport } from './routes/_authenticated/dashboard.ugc.$businessId'
import { Route as AuthenticatedDashboardStorefrontBusinessIdRouteImport } from './routes/_authenticated/dashboard.storefront.$businessId'
import { Route as AuthenticatedDashboardProductsNewRouteImport } from './routes/_authenticated/dashboard.products.new'
import { Route as AuthenticatedDashboardProductsProductIdRouteImport } from './routes/_authenticated/dashboard.products.$productId'
import { Route as AuthenticatedDashboardPostsBusinessIdRouteImport } from './routes/_authenticated/dashboard.posts.$businessId'
import { Route as AuthenticatedDashboardIntegrationsPixelsRouteImport } from './routes/_authenticated/dashboard.integrations.pixels'
import { Route as AuthenticatedDashboardIntegrationsMetaRouteImport } from './routes/_authenticated/dashboard.integrations.meta'
import { Route as AuthenticatedDashboardImagesBusinessIdRouteImport } from './routes/_authenticated/dashboard.images.$businessId'
import { Route as AuthenticatedDashboardEmailsBusinessIdRouteImport } from './routes/_authenticated/dashboard.emails.$businessId'
import { Route as AuthenticatedDashboardEmailCampaignsRouteImport } from './routes/_authenticated/dashboard.email.campaigns'
import { Route as AuthenticatedDashboardEmailAutomationsRouteImport } from './routes/_authenticated/dashboard.email.automations'
import { Route as AuthenticatedDashboardContentVideoRouteImport } from './routes/_authenticated/dashboard.content.video'
import { Route as AuthenticatedDashboardContentUgcRouteImport } from './routes/_authenticated/dashboard.content.ugc'
import { Route as AuthenticatedDashboardContentImageRouteImport } from './routes/_authenticated/dashboard.content.image'
import { Route as AuthenticatedDashboardContactsBusinessIdRouteImport } from './routes/_authenticated/dashboard.contacts.$businessId'
import { Route as AuthenticatedDashboardAutomationsBusinessIdRouteImport } from './routes/_authenticated/dashboard.automations.$businessId'
import { Route as AuthenticatedDashboardAnalyticsBusinessIdRouteImport } from './routes/_authenticated/dashboard.analytics.$businessId'
import { Route as AuthenticatedDashboardAdsNewRouteImport } from './routes/_authenticated/dashboard.ads.new'
import { Route as AuthenticatedDashboardAdsIdRouteImport } from './routes/_authenticated/dashboard.ads.$id'
import { Route as AuthenticatedDashboardEmailCampaignsIndexRouteImport } from './routes/_authenticated/dashboard.email.campaigns.index'
import { Route as AuthenticatedDashboardEmailAutomationsIndexRouteImport } from './routes/_authenticated/dashboard.email.automations.index'
import { Route as AuthenticatedDashboardEmailCampaignsNewRouteImport } from './routes/_authenticated/dashboard.email.campaigns.new'
import { Route as AuthenticatedDashboardEmailCampaignsIdRouteImport } from './routes/_authenticated/dashboard.email.campaigns.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCodeRoute = PayCodeRouteImport.update({
  id: '/pay/$code',
  path: '/pay/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing-webhook',
  path: '/api/public/billing-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardVideosRoute =
  AuthenticatedDashboardVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUgcRoute =
  AuthenticatedDashboardUgcRouteImport.update({
    id: '/ugc',
    path: '/ugc',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStorefrontRoute =
  AuthenticatedDashboardStorefrontRouteImport.update({
    id: '/storefront',
    path: '/storefront',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsRoute =
  AuthenticatedDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPostsRoute =
  AuthenticatedDashboardPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPayoutsRoute =
  AuthenticatedDashboardPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentLinksRoute =
  AuthenticatedDashboardPaymentLinksRouteImport.update({
    id: '/payment-links',
    path: '/payment-links',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNewRoute =
  AuthenticatedDashboardNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardImagesRoute =
  AuthenticatedDashboardImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEmailsRoute =
  AuthenticatedDashboardEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEmailRoute =
  AuthenticatedDashboardEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEarningsRoute =
  AuthenticatedDashboardEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContentRoute =
  AuthenticatedDashboardContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContactsRoute =
  AuthenticatedDashboardContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAutomationsRoute =
  AuthenticatedDashboardAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdsRoute =
  AuthenticatedDashboardAdsRouteImport.update({
    id: '/ads',
    path: '/ads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsIndexRoute =
  AuthenticatedDashboardProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardProductsRoute,
  } as any)
const AuthenticatedDashboardContentIndexRoute =
  AuthenticatedDashboardContentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardContentRoute,
  } as any)
const AuthenticatedDashboardAdsIndexRoute =
  AuthenticatedDashboardAdsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdsRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardVideosBusinessIdRoute =
  AuthenticatedDashboardVideosBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardVideosRoute,
  } as any)
const AuthenticatedDashboardUgcBusinessIdRoute =
  AuthenticatedDashboardUgcBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardUgcRoute,
  } as any)
const AuthenticatedDashboardStorefrontBusinessIdRoute =
  AuthenticatedDashboardStorefrontBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardStorefrontRoute,
  } as any)
const AuthenticatedDashboardProductsNewRoute =
  AuthenticatedDashboardProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardProductsRoute,
  } as any)
const AuthenticatedDashboardProductsProductIdRoute =
  AuthenticatedDashboardProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedDashboardProductsRoute,
  } as any)
const AuthenticatedDashboardPostsBusinessIdRoute =
  AuthenticatedDashboardPostsBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardPostsRoute,
  } as any)
const AuthenticatedDashboardIntegrationsPixelsRoute =
  AuthenticatedDashboardIntegrationsPixelsRouteImport.update({
    id: '/integrations/pixels',
    path: '/integrations/pixels',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsMetaRoute =
  AuthenticatedDashboardIntegrationsMetaRouteImport.update({
    id: '/integrations/meta',
    path: '/integrations/meta',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardImagesBusinessIdRoute =
  AuthenticatedDashboardImagesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardImagesRoute,
  } as any)
const AuthenticatedDashboardEmailsBusinessIdRoute =
  AuthenticatedDashboardEmailsBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardEmailsRoute,
  } as any)
const AuthenticatedDashboardEmailCampaignsRoute =
  AuthenticatedDashboardEmailCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedDashboardEmailRoute,
  } as any)
const AuthenticatedDashboardEmailAutomationsRoute =
  AuthenticatedDashboardEmailAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedDashboardEmailRoute,
  } as any)
const AuthenticatedDashboardContentVideoRoute =
  AuthenticatedDashboardContentVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AuthenticatedDashboardContentRoute,
  } as any)
const AuthenticatedDashboardContentUgcRoute =
  AuthenticatedDashboardContentUgcRouteImport.update({
    id: '/ugc',
    path: '/ugc',
    getParentRoute: () => AuthenticatedDashboardContentRoute,
  } as any)
const AuthenticatedDashboardContentImageRoute =
  AuthenticatedDashboardContentImageRouteImport.update({
    id: '/image',
    path: '/image',
    getParentRoute: () => AuthenticatedDashboardContentRoute,
  } as any)
const AuthenticatedDashboardContactsBusinessIdRoute =
  AuthenticatedDashboardContactsBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardContactsRoute,
  } as any)
const AuthenticatedDashboardAutomationsBusinessIdRoute =
  AuthenticatedDashboardAutomationsBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardAutomationsRoute,
  } as any)
const AuthenticatedDashboardAnalyticsBusinessIdRoute =
  AuthenticatedDashboardAnalyticsBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedDashboardAnalyticsRoute,
  } as any)
const AuthenticatedDashboardAdsNewRoute =
  AuthenticatedDashboardAdsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardAdsRoute,
  } as any)
const AuthenticatedDashboardAdsIdRoute =
  AuthenticatedDashboardAdsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardAdsRoute,
  } as any)
const AuthenticatedDashboardEmailCampaignsIndexRoute =
  AuthenticatedDashboardEmailCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardEmailCampaignsRoute,
  } as any)
const AuthenticatedDashboardEmailAutomationsIndexRoute =
  AuthenticatedDashboardEmailAutomationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardEmailAutomationsRoute,
  } as any)
const AuthenticatedDashboardEmailCampaignsNewRoute =
  AuthenticatedDashboardEmailCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardEmailCampaignsRoute,
  } as any)
const AuthenticatedDashboardEmailCampaignsIdRoute =
  AuthenticatedDashboardEmailCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardEmailCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/pay/$code': typeof PayCodeRoute
  '/s/$slug': typeof SSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/dashboard/ads': typeof AuthenticatedDashboardAdsRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRouteWithChildren
  '/dashboard/automations': typeof AuthenticatedDashboardAutomationsRouteWithChildren
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/contacts': typeof AuthenticatedDashboardContactsRouteWithChildren
  '/dashboard/content': typeof AuthenticatedDashboardContentRouteWithChildren
  '/dashboard/earnings': typeof AuthenticatedDashboardEarningsRoute
  '/dashboard/email': typeof AuthenticatedDashboardEmailRouteWithChildren
  '/dashboard/emails': typeof AuthenticatedDashboardEmailsRouteWithChildren
  '/dashboard/images': typeof AuthenticatedDashboardImagesRouteWithChildren
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/posts': typeof AuthenticatedDashboardPostsRouteWithChildren
  '/dashboard/products': typeof AuthenticatedDashboardProductsRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/storefront': typeof AuthenticatedDashboardStorefrontRouteWithChildren
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/ugc': typeof AuthenticatedDashboardUgcRouteWithChildren
  '/dashboard/videos': typeof AuthenticatedDashboardVideosRouteWithChildren
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/ads/$id': typeof AuthenticatedDashboardAdsIdRoute
  '/dashboard/ads/new': typeof AuthenticatedDashboardAdsNewRoute
  '/dashboard/analytics/$businessId': typeof AuthenticatedDashboardAnalyticsBusinessIdRoute
  '/dashboard/automations/$businessId': typeof AuthenticatedDashboardAutomationsBusinessIdRoute
  '/dashboard/contacts/$businessId': typeof AuthenticatedDashboardContactsBusinessIdRoute
  '/dashboard/content/image': typeof AuthenticatedDashboardContentImageRoute
  '/dashboard/content/ugc': typeof AuthenticatedDashboardContentUgcRoute
  '/dashboard/content/video': typeof AuthenticatedDashboardContentVideoRoute
  '/dashboard/email/automations': typeof AuthenticatedDashboardEmailAutomationsRouteWithChildren
  '/dashboard/email/campaigns': typeof AuthenticatedDashboardEmailCampaignsRouteWithChildren
  '/dashboard/emails/$businessId': typeof AuthenticatedDashboardEmailsBusinessIdRoute
  '/dashboard/images/$businessId': typeof AuthenticatedDashboardImagesBusinessIdRoute
  '/dashboard/integrations/meta': typeof AuthenticatedDashboardIntegrationsMetaRoute
  '/dashboard/integrations/pixels': typeof AuthenticatedDashboardIntegrationsPixelsRoute
  '/dashboard/posts/$businessId': typeof AuthenticatedDashboardPostsBusinessIdRoute
  '/dashboard/products/$productId': typeof AuthenticatedDashboardProductsProductIdRoute
  '/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/dashboard/storefront/$businessId': typeof AuthenticatedDashboardStorefrontBusinessIdRoute
  '/dashboard/ugc/$businessId': typeof AuthenticatedDashboardUgcBusinessIdRoute
  '/dashboard/videos/$businessId': typeof AuthenticatedDashboardVideosBusinessIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/ads/': typeof AuthenticatedDashboardAdsIndexRoute
  '/dashboard/content/': typeof AuthenticatedDashboardContentIndexRoute
  '/dashboard/products/': typeof AuthenticatedDashboardProductsIndexRoute
  '/dashboard/email/campaigns/$id': typeof AuthenticatedDashboardEmailCampaignsIdRoute
  '/dashboard/email/campaigns/new': typeof AuthenticatedDashboardEmailCampaignsNewRoute
  '/dashboard/email/automations/': typeof AuthenticatedDashboardEmailAutomationsIndexRoute
  '/dashboard/email/campaigns/': typeof AuthenticatedDashboardEmailCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/pay/$code': typeof PayCodeRoute
  '/s/$slug': typeof SSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRouteWithChildren
  '/dashboard/automations': typeof AuthenticatedDashboardAutomationsRouteWithChildren
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/contacts': typeof AuthenticatedDashboardContactsRouteWithChildren
  '/dashboard/earnings': typeof AuthenticatedDashboardEarningsRoute
  '/dashboard/email': typeof AuthenticatedDashboardEmailRouteWithChildren
  '/dashboard/emails': typeof AuthenticatedDashboardEmailsRouteWithChildren
  '/dashboard/images': typeof AuthenticatedDashboardImagesRouteWithChildren
  '/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/posts': typeof AuthenticatedDashboardPostsRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/storefront': typeof AuthenticatedDashboardStorefrontRouteWithChildren
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/ugc': typeof AuthenticatedDashboardUgcRouteWithChildren
  '/dashboard/videos': typeof AuthenticatedDashboardVideosRouteWithChildren
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/ads/$id': typeof AuthenticatedDashboardAdsIdRoute
  '/dashboard/ads/new': typeof AuthenticatedDashboardAdsNewRoute
  '/dashboard/analytics/$businessId': typeof AuthenticatedDashboardAnalyticsBusinessIdRoute
  '/dashboard/automations/$businessId': typeof AuthenticatedDashboardAutomationsBusinessIdRoute
  '/dashboard/contacts/$businessId': typeof AuthenticatedDashboardContactsBusinessIdRoute
  '/dashboard/content/image': typeof AuthenticatedDashboardContentImageRoute
  '/dashboard/content/ugc': typeof AuthenticatedDashboardContentUgcRoute
  '/dashboard/content/video': typeof AuthenticatedDashboardContentVideoRoute
  '/dashboard/emails/$businessId': typeof AuthenticatedDashboardEmailsBusinessIdRoute
  '/dashboard/images/$businessId': typeof AuthenticatedDashboardImagesBusinessIdRoute
  '/dashboard/integrations/meta': typeof AuthenticatedDashboardIntegrationsMetaRoute
  '/dashboard/integrations/pixels': typeof AuthenticatedDashboardIntegrationsPixelsRoute
  '/dashboard/posts/$businessId': typeof AuthenticatedDashboardPostsBusinessIdRoute
  '/dashboard/products/$productId': typeof AuthenticatedDashboardProductsProductIdRoute
  '/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/dashboard/storefront/$businessId': typeof AuthenticatedDashboardStorefrontBusinessIdRoute
  '/dashboard/ugc/$businessId': typeof AuthenticatedDashboardUgcBusinessIdRoute
  '/dashboard/videos/$businessId': typeof AuthenticatedDashboardVideosBusinessIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/ads': typeof AuthenticatedDashboardAdsIndexRoute
  '/dashboard/content': typeof AuthenticatedDashboardContentIndexRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsIndexRoute
  '/dashboard/email/campaigns/$id': typeof AuthenticatedDashboardEmailCampaignsIdRoute
  '/dashboard/email/campaigns/new': typeof AuthenticatedDashboardEmailCampaignsNewRoute
  '/dashboard/email/automations': typeof AuthenticatedDashboardEmailAutomationsIndexRoute
  '/dashboard/email/campaigns': typeof AuthenticatedDashboardEmailCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/pay/$code': typeof PayCodeRoute
  '/s/$slug': typeof SSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/_authenticated/dashboard/ads': typeof AuthenticatedDashboardAdsRouteWithChildren
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRouteWithChildren
  '/_authenticated/dashboard/automations': typeof AuthenticatedDashboardAutomationsRouteWithChildren
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/contacts': typeof AuthenticatedDashboardContactsRouteWithChildren
  '/_authenticated/dashboard/content': typeof AuthenticatedDashboardContentRouteWithChildren
  '/_authenticated/dashboard/earnings': typeof AuthenticatedDashboardEarningsRoute
  '/_authenticated/dashboard/email': typeof AuthenticatedDashboardEmailRouteWithChildren
  '/_authenticated/dashboard/emails': typeof AuthenticatedDashboardEmailsRouteWithChildren
  '/_authenticated/dashboard/images': typeof AuthenticatedDashboardImagesRouteWithChildren
  '/_authenticated/dashboard/new': typeof AuthenticatedDashboardNewRoute
  '/_authenticated/dashboard/payment-links': typeof AuthenticatedDashboardPaymentLinksRoute
  '/_authenticated/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/_authenticated/dashboard/posts': typeof AuthenticatedDashboardPostsRouteWithChildren
  '/_authenticated/dashboard/products': typeof AuthenticatedDashboardProductsRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/storefront': typeof AuthenticatedDashboardStorefrontRouteWithChildren
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/ugc': typeof AuthenticatedDashboardUgcRouteWithChildren
  '/_authenticated/dashboard/videos': typeof AuthenticatedDashboardVideosRouteWithChildren
  '/api/public/billing-webhook': typeof ApiPublicBillingWebhookRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/ads/$id': typeof AuthenticatedDashboardAdsIdRoute
  '/_authenticated/dashboard/ads/new': typeof AuthenticatedDashboardAdsNewRoute
  '/_authenticated/dashboard/analytics/$businessId': typeof AuthenticatedDashboardAnalyticsBusinessIdRoute
  '/_authenticated/dashboard/automations/$businessId': typeof AuthenticatedDashboardAutomationsBusinessIdRoute
  '/_authenticated/dashboard/contacts/$businessId': typeof AuthenticatedDashboardContactsBusinessIdRoute
  '/_authenticated/dashboard/content/image': typeof AuthenticatedDashboardContentImageRoute
  '/_authenticated/dashboard/content/ugc': typeof AuthenticatedDashboardContentUgcRoute
  '/_authenticated/dashboard/content/video': typeof AuthenticatedDashboardContentVideoRoute
  '/_authenticated/dashboard/email/automations': typeof AuthenticatedDashboardEmailAutomationsRouteWithChildren
  '/_authenticated/dashboard/email/campaigns': typeof AuthenticatedDashboardEmailCampaignsRouteWithChildren
  '/_authenticated/dashboard/emails/$businessId': typeof AuthenticatedDashboardEmailsBusinessIdRoute
  '/_authenticated/dashboard/images/$businessId': typeof AuthenticatedDashboardImagesBusinessIdRoute
  '/_authenticated/dashboard/integrations/meta': typeof AuthenticatedDashboardIntegrationsMetaRoute
  '/_authenticated/dashboard/integrations/pixels': typeof AuthenticatedDashboardIntegrationsPixelsRoute
  '/_authenticated/dashboard/posts/$businessId': typeof AuthenticatedDashboardPostsBusinessIdRoute
  '/_authenticated/dashboard/products/$productId': typeof AuthenticatedDashboardProductsProductIdRoute
  '/_authenticated/dashboard/products/new': typeof AuthenticatedDashboardProductsNewRoute
  '/_authenticated/dashboard/storefront/$businessId': typeof AuthenticatedDashboardStorefrontBusinessIdRoute
  '/_authenticated/dashboard/ugc/$businessId': typeof AuthenticatedDashboardUgcBusinessIdRoute
  '/_authenticated/dashboard/videos/$businessId': typeof AuthenticatedDashboardVideosBusinessIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/dashboard/ads/': typeof AuthenticatedDashboardAdsIndexRoute
  '/_authenticated/dashboard/content/': typeof AuthenticatedDashboardContentIndexRoute
  '/_authenticated/dashboard/products/': typeof AuthenticatedDashboardProductsIndexRoute
  '/_authenticated/dashboard/email/campaigns/$id': typeof AuthenticatedDashboardEmailCampaignsIdRoute
  '/_authenticated/dashboard/email/campaigns/new': typeof AuthenticatedDashboardEmailCampaignsNewRoute
  '/_authenticated/dashboard/email/automations/': typeof AuthenticatedDashboardEmailAutomationsIndexRoute
  '/_authenticated/dashboard/email/campaigns/': typeof AuthenticatedDashboardEmailCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/pay/$code'
    | '/s/$slug'
    | '/unsubscribe/$token'
    | '/dashboard/ads'
    | '/dashboard/analytics'
    | '/dashboard/automations'
    | '/dashboard/billing'
    | '/dashboard/contacts'
    | '/dashboard/content'
    | '/dashboard/earnings'
    | '/dashboard/email'
    | '/dashboard/emails'
    | '/dashboard/images'
    | '/dashboard/new'
    | '/dashboard/payment-links'
    | '/dashboard/payouts'
    | '/dashboard/posts'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/dashboard/transactions'
    | '/dashboard/ugc'
    | '/dashboard/videos'
    | '/api/public/billing-webhook'
    | '/dashboard/'
    | '/dashboard/ads/$id'
    | '/dashboard/ads/new'
    | '/dashboard/analytics/$businessId'
    | '/dashboard/automations/$businessId'
    | '/dashboard/contacts/$businessId'
    | '/dashboard/content/image'
    | '/dashboard/content/ugc'
    | '/dashboard/content/video'
    | '/dashboard/email/automations'
    | '/dashboard/email/campaigns'
    | '/dashboard/emails/$businessId'
    | '/dashboard/images/$businessId'
    | '/dashboard/integrations/meta'
    | '/dashboard/integrations/pixels'
    | '/dashboard/posts/$businessId'
    | '/dashboard/products/$productId'
    | '/dashboard/products/new'
    | '/dashboard/storefront/$businessId'
    | '/dashboard/ugc/$businessId'
    | '/dashboard/videos/$businessId'
    | '/api/public/payments/webhook'
    | '/dashboard/ads/'
    | '/dashboard/content/'
    | '/dashboard/products/'
    | '/dashboard/email/campaigns/$id'
    | '/dashboard/email/campaigns/new'
    | '/dashboard/email/automations/'
    | '/dashboard/email/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/pay/$code'
    | '/s/$slug'
    | '/unsubscribe/$token'
    | '/dashboard/analytics'
    | '/dashboard/automations'
    | '/dashboard/billing'
    | '/dashboard/contacts'
    | '/dashboard/earnings'
    | '/dashboard/email'
    | '/dashboard/emails'
    | '/dashboard/images'
    | '/dashboard/new'
    | '/dashboard/payment-links'
    | '/dashboard/payouts'
    | '/dashboard/posts'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/dashboard/transactions'
    | '/dashboard/ugc'
    | '/dashboard/videos'
    | '/api/public/billing-webhook'
    | '/dashboard'
    | '/dashboard/ads/$id'
    | '/dashboard/ads/new'
    | '/dashboard/analytics/$businessId'
    | '/dashboard/automations/$businessId'
    | '/dashboard/contacts/$businessId'
    | '/dashboard/content/image'
    | '/dashboard/content/ugc'
    | '/dashboard/content/video'
    | '/dashboard/emails/$businessId'
    | '/dashboard/images/$businessId'
    | '/dashboard/integrations/meta'
    | '/dashboard/integrations/pixels'
    | '/dashboard/posts/$businessId'
    | '/dashboard/products/$productId'
    | '/dashboard/products/new'
    | '/dashboard/storefront/$businessId'
    | '/dashboard/ugc/$businessId'
    | '/dashboard/videos/$businessId'
    | '/api/public/payments/webhook'
    | '/dashboard/ads'
    | '/dashboard/content'
    | '/dashboard/products'
    | '/dashboard/email/campaigns/$id'
    | '/dashboard/email/campaigns/new'
    | '/dashboard/email/automations'
    | '/dashboard/email/campaigns'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/pay/$code'
    | '/s/$slug'
    | '/unsubscribe/$token'
    | '/_authenticated/dashboard/ads'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/automations'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/contacts'
    | '/_authenticated/dashboard/content'
    | '/_authenticated/dashboard/earnings'
    | '/_authenticated/dashboard/email'
    | '/_authenticated/dashboard/emails'
    | '/_authenticated/dashboard/images'
    | '/_authenticated/dashboard/new'
    | '/_authenticated/dashboard/payment-links'
    | '/_authenticated/dashboard/payouts'
    | '/_authenticated/dashboard/posts'
    | '/_authenticated/dashboard/products'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/storefront'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/ugc'
    | '/_authenticated/dashboard/videos'
    | '/api/public/billing-webhook'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/ads/$id'
    | '/_authenticated/dashboard/ads/new'
    | '/_authenticated/dashboard/analytics/$businessId'
    | '/_authenticated/dashboard/automations/$businessId'
    | '/_authenticated/dashboard/contacts/$businessId'
    | '/_authenticated/dashboard/content/image'
    | '/_authenticated/dashboard/content/ugc'
    | '/_authenticated/dashboard/content/video'
    | '/_authenticated/dashboard/email/automations'
    | '/_authenticated/dashboard/email/campaigns'
    | '/_authenticated/dashboard/emails/$businessId'
    | '/_authenticated/dashboard/images/$businessId'
    | '/_authenticated/dashboard/integrations/meta'
    | '/_authenticated/dashboard/integrations/pixels'
    | '/_authenticated/dashboard/posts/$businessId'
    | '/_authenticated/dashboard/products/$productId'
    | '/_authenticated/dashboard/products/new'
    | '/_authenticated/dashboard/storefront/$businessId'
    | '/_authenticated/dashboard/ugc/$businessId'
    | '/_authenticated/dashboard/videos/$businessId'
    | '/api/public/payments/webhook'
    | '/_authenticated/dashboard/ads/'
    | '/_authenticated/dashboard/content/'
    | '/_authenticated/dashboard/products/'
    | '/_authenticated/dashboard/email/campaigns/$id'
    | '/_authenticated/dashboard/email/campaigns/new'
    | '/_authenticated/dashboard/email/automations/'
    | '/_authenticated/dashboard/email/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PayCodeRoute: typeof PayCodeRoute
  SSlugRoute: typeof SSlugRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$code': {
      id: '/pay/$code'
      path: '/pay/$code'
      fullPath: '/pay/$code'
      preLoaderRoute: typeof PayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/billing-webhook': {
      id: '/api/public/billing-webhook'
      path: '/api/public/billing-webhook'
      fullPath: '/api/public/billing-webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/videos': {
      id: '/_authenticated/dashboard/videos'
      path: '/videos'
      fullPath: '/dashboard/videos'
      preLoaderRoute: typeof AuthenticatedDashboardVideosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ugc': {
      id: '/_authenticated/dashboard/ugc'
      path: '/ugc'
      fullPath: '/dashboard/ugc'
      preLoaderRoute: typeof AuthenticatedDashboardUgcRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/storefront': {
      id: '/_authenticated/dashboard/storefront'
      path: '/storefront'
      fullPath: '/dashboard/storefront'
      preLoaderRoute: typeof AuthenticatedDashboardStorefrontRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products': {
      id: '/_authenticated/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/posts': {
      id: '/_authenticated/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof AuthenticatedDashboardPostsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payouts': {
      id: '/_authenticated/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof AuthenticatedDashboardPayoutsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payment-links': {
      id: '/_authenticated/dashboard/payment-links'
      path: '/payment-links'
      fullPath: '/dashboard/payment-links'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentLinksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/new': {
      id: '/_authenticated/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AuthenticatedDashboardNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/images': {
      id: '/_authenticated/dashboard/images'
      path: '/images'
      fullPath: '/dashboard/images'
      preLoaderRoute: typeof AuthenticatedDashboardImagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/emails': {
      id: '/_authenticated/dashboard/emails'
      path: '/emails'
      fullPath: '/dashboard/emails'
      preLoaderRoute: typeof AuthenticatedDashboardEmailsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/email': {
      id: '/_authenticated/dashboard/email'
      path: '/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof AuthenticatedDashboardEmailRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/earnings': {
      id: '/_authenticated/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof AuthenticatedDashboardEarningsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/content': {
      id: '/_authenticated/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof AuthenticatedDashboardContentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/contacts': {
      id: '/_authenticated/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof AuthenticatedDashboardContactsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/automations': {
      id: '/_authenticated/dashboard/automations'
      path: '/automations'
      fullPath: '/dashboard/automations'
      preLoaderRoute: typeof AuthenticatedDashboardAutomationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ads': {
      id: '/_authenticated/dashboard/ads'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof AuthenticatedDashboardAdsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products/': {
      id: '/_authenticated/dashboard/products/'
      path: '/'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof AuthenticatedDashboardProductsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProductsRoute
    }
    '/_authenticated/dashboard/content/': {
      id: '/_authenticated/dashboard/content/'
      path: '/'
      fullPath: '/dashboard/content/'
      preLoaderRoute: typeof AuthenticatedDashboardContentIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardContentRoute
    }
    '/_authenticated/dashboard/ads/': {
      id: '/_authenticated/dashboard/ads/'
      path: '/'
      fullPath: '/dashboard/ads/'
      preLoaderRoute: typeof AuthenticatedDashboardAdsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/videos/$businessId': {
      id: '/_authenticated/dashboard/videos/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/videos/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardVideosBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardVideosRoute
    }
    '/_authenticated/dashboard/ugc/$businessId': {
      id: '/_authenticated/dashboard/ugc/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/ugc/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardUgcBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardUgcRoute
    }
    '/_authenticated/dashboard/storefront/$businessId': {
      id: '/_authenticated/dashboard/storefront/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/storefront/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardStorefrontBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardStorefrontRoute
    }
    '/_authenticated/dashboard/products/new': {
      id: '/_authenticated/dashboard/products/new'
      path: '/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof AuthenticatedDashboardProductsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardProductsRoute
    }
    '/_authenticated/dashboard/products/$productId': {
      id: '/_authenticated/dashboard/products/$productId'
      path: '/$productId'
      fullPath: '/dashboard/products/$productId'
      preLoaderRoute: typeof AuthenticatedDashboardProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedDashboardProductsRoute
    }
    '/_authenticated/dashboard/posts/$businessId': {
      id: '/_authenticated/dashboard/posts/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/posts/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardPostsBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardPostsRoute
    }
    '/_authenticated/dashboard/integrations/pixels': {
      id: '/_authenticated/dashboard/integrations/pixels'
      path: '/integrations/pixels'
      fullPath: '/dashboard/integrations/pixels'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsPixelsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations/meta': {
      id: '/_authenticated/dashboard/integrations/meta'
      path: '/integrations/meta'
      fullPath: '/dashboard/integrations/meta'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsMetaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/images/$businessId': {
      id: '/_authenticated/dashboard/images/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/images/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardImagesBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardImagesRoute
    }
    '/_authenticated/dashboard/emails/$businessId': {
      id: '/_authenticated/dashboard/emails/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/emails/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardEmailsBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailsRoute
    }
    '/_authenticated/dashboard/email/campaigns': {
      id: '/_authenticated/dashboard/email/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/email/campaigns'
      preLoaderRoute: typeof AuthenticatedDashboardEmailCampaignsRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailRoute
    }
    '/_authenticated/dashboard/email/automations': {
      id: '/_authenticated/dashboard/email/automations'
      path: '/automations'
      fullPath: '/dashboard/email/automations'
      preLoaderRoute: typeof AuthenticatedDashboardEmailAutomationsRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailRoute
    }
    '/_authenticated/dashboard/content/video': {
      id: '/_authenticated/dashboard/content/video'
      path: '/video'
      fullPath: '/dashboard/content/video'
      preLoaderRoute: typeof AuthenticatedDashboardContentVideoRouteImport
      parentRoute: typeof AuthenticatedDashboardContentRoute
    }
    '/_authenticated/dashboard/content/ugc': {
      id: '/_authenticated/dashboard/content/ugc'
      path: '/ugc'
      fullPath: '/dashboard/content/ugc'
      preLoaderRoute: typeof AuthenticatedDashboardContentUgcRouteImport
      parentRoute: typeof AuthenticatedDashboardContentRoute
    }
    '/_authenticated/dashboard/content/image': {
      id: '/_authenticated/dashboard/content/image'
      path: '/image'
      fullPath: '/dashboard/content/image'
      preLoaderRoute: typeof AuthenticatedDashboardContentImageRouteImport
      parentRoute: typeof AuthenticatedDashboardContentRoute
    }
    '/_authenticated/dashboard/contacts/$businessId': {
      id: '/_authenticated/dashboard/contacts/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/contacts/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardContactsBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardContactsRoute
    }
    '/_authenticated/dashboard/automations/$businessId': {
      id: '/_authenticated/dashboard/automations/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/automations/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardAutomationsBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardAutomationsRoute
    }
    '/_authenticated/dashboard/analytics/$businessId': {
      id: '/_authenticated/dashboard/analytics/$businessId'
      path: '/$businessId'
      fullPath: '/dashboard/analytics/$businessId'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsBusinessIdRouteImport
      parentRoute: typeof AuthenticatedDashboardAnalyticsRoute
    }
    '/_authenticated/dashboard/ads/new': {
      id: '/_authenticated/dashboard/ads/new'
      path: '/new'
      fullPath: '/dashboard/ads/new'
      preLoaderRoute: typeof AuthenticatedDashboardAdsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardAdsRoute
    }
    '/_authenticated/dashboard/ads/$id': {
      id: '/_authenticated/dashboard/ads/$id'
      path: '/$id'
      fullPath: '/dashboard/ads/$id'
      preLoaderRoute: typeof AuthenticatedDashboardAdsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardAdsRoute
    }
    '/_authenticated/dashboard/email/campaigns/': {
      id: '/_authenticated/dashboard/email/campaigns/'
      path: '/'
      fullPath: '/dashboard/email/campaigns/'
      preLoaderRoute: typeof AuthenticatedDashboardEmailCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailCampaignsRoute
    }
    '/_authenticated/dashboard/email/automations/': {
      id: '/_authenticated/dashboard/email/automations/'
      path: '/'
      fullPath: '/dashboard/email/automations/'
      preLoaderRoute: typeof AuthenticatedDashboardEmailAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailAutomationsRoute
    }
    '/_authenticated/dashboard/email/campaigns/new': {
      id: '/_authenticated/dashboard/email/campaigns/new'
      path: '/new'
      fullPath: '/dashboard/email/campaigns/new'
      preLoaderRoute: typeof AuthenticatedDashboardEmailCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailCampaignsRoute
    }
    '/_authenticated/dashboard/email/campaigns/$id': {
      id: '/_authenticated/dashboard/email/campaigns/$id'
      path: '/$id'
      fullPath: '/dashboard/email/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedDashboardEmailCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardEmailCampaignsRoute
    }
  }
}

interface AuthenticatedDashboardAdsRouteChildren {
  AuthenticatedDashboardAdsIdRoute: typeof AuthenticatedDashboardAdsIdRoute
  AuthenticatedDashboardAdsNewRoute: typeof AuthenticatedDashboardAdsNewRoute
  AuthenticatedDashboardAdsIndexRoute: typeof AuthenticatedDashboardAdsIndexRoute
}

const AuthenticatedDashboardAdsRouteChildren: AuthenticatedDashboardAdsRouteChildren =
  {
    AuthenticatedDashboardAdsIdRoute: AuthenticatedDashboardAdsIdRoute,
    AuthenticatedDashboardAdsNewRoute: AuthenticatedDashboardAdsNewRoute,
    AuthenticatedDashboardAdsIndexRoute: AuthenticatedDashboardAdsIndexRoute,
  }

const AuthenticatedDashboardAdsRouteWithChildren =
  AuthenticatedDashboardAdsRoute._addFileChildren(
    AuthenticatedDashboardAdsRouteChildren,
  )

interface AuthenticatedDashboardAnalyticsRouteChildren {
  AuthenticatedDashboardAnalyticsBusinessIdRoute: typeof AuthenticatedDashboardAnalyticsBusinessIdRoute
}

const AuthenticatedDashboardAnalyticsRouteChildren: AuthenticatedDashboardAnalyticsRouteChildren =
  {
    AuthenticatedDashboardAnalyticsBusinessIdRoute:
      AuthenticatedDashboardAnalyticsBusinessIdRoute,
  }

const AuthenticatedDashboardAnalyticsRouteWithChildren =
  AuthenticatedDashboardAnalyticsRoute._addFileChildren(
    AuthenticatedDashboardAnalyticsRouteChildren,
  )

interface AuthenticatedDashboardAutomationsRouteChildren {
  AuthenticatedDashboardAutomationsBusinessIdRoute: typeof AuthenticatedDashboardAutomationsBusinessIdRoute
}

const AuthenticatedDashboardAutomationsRouteChildren: AuthenticatedDashboardAutomationsRouteChildren =
  {
    AuthenticatedDashboardAutomationsBusinessIdRoute:
      AuthenticatedDashboardAutomationsBusinessIdRoute,
  }

const AuthenticatedDashboardAutomationsRouteWithChildren =
  AuthenticatedDashboardAutomationsRoute._addFileChildren(
    AuthenticatedDashboardAutomationsRouteChildren,
  )

interface AuthenticatedDashboardContactsRouteChildren {
  AuthenticatedDashboardContactsBusinessIdRoute: typeof AuthenticatedDashboardContactsBusinessIdRoute
}

const AuthenticatedDashboardContactsRouteChildren: AuthenticatedDashboardContactsRouteChildren =
  {
    AuthenticatedDashboardContactsBusinessIdRoute:
      AuthenticatedDashboardContactsBusinessIdRoute,
  }

const AuthenticatedDashboardContactsRouteWithChildren =
  AuthenticatedDashboardContactsRoute._addFileChildren(
    AuthenticatedDashboardContactsRouteChildren,
  )

interface AuthenticatedDashboardContentRouteChildren {
  AuthenticatedDashboardContentImageRoute: typeof AuthenticatedDashboardContentImageRoute
  AuthenticatedDashboardContentUgcRoute: typeof AuthenticatedDashboardContentUgcRoute
  AuthenticatedDashboardContentVideoRoute: typeof AuthenticatedDashboardContentVideoRoute
  AuthenticatedDashboardContentIndexRoute: typeof AuthenticatedDashboardContentIndexRoute
}

const AuthenticatedDashboardContentRouteChildren: AuthenticatedDashboardContentRouteChildren =
  {
    AuthenticatedDashboardContentImageRoute:
      AuthenticatedDashboardContentImageRoute,
    AuthenticatedDashboardContentUgcRoute:
      AuthenticatedDashboardContentUgcRoute,
    AuthenticatedDashboardContentVideoRoute:
      AuthenticatedDashboardContentVideoRoute,
    AuthenticatedDashboardContentIndexRoute:
      AuthenticatedDashboardContentIndexRoute,
  }

const AuthenticatedDashboardContentRouteWithChildren =
  AuthenticatedDashboardContentRoute._addFileChildren(
    AuthenticatedDashboardContentRouteChildren,
  )

interface AuthenticatedDashboardEmailAutomationsRouteChildren {
  AuthenticatedDashboardEmailAutomationsIndexRoute: typeof AuthenticatedDashboardEmailAutomationsIndexRoute
}

const AuthenticatedDashboardEmailAutomationsRouteChildren: AuthenticatedDashboardEmailAutomationsRouteChildren =
  {
    AuthenticatedDashboardEmailAutomationsIndexRoute:
      AuthenticatedDashboardEmailAutomationsIndexRoute,
  }

const AuthenticatedDashboardEmailAutomationsRouteWithChildren =
  AuthenticatedDashboardEmailAutomationsRoute._addFileChildren(
    AuthenticatedDashboardEmailAutomationsRouteChildren,
  )

interface AuthenticatedDashboardEmailCampaignsRouteChildren {
  AuthenticatedDashboardEmailCampaignsIdRoute: typeof AuthenticatedDashboardEmailCampaignsIdRoute
  AuthenticatedDashboardEmailCampaignsNewRoute: typeof AuthenticatedDashboardEmailCampaignsNewRoute
  AuthenticatedDashboardEmailCampaignsIndexRoute: typeof AuthenticatedDashboardEmailCampaignsIndexRoute
}

const AuthenticatedDashboardEmailCampaignsRouteChildren: AuthenticatedDashboardEmailCampaignsRouteChildren =
  {
    AuthenticatedDashboardEmailCampaignsIdRoute:
      AuthenticatedDashboardEmailCampaignsIdRoute,
    AuthenticatedDashboardEmailCampaignsNewRoute:
      AuthenticatedDashboardEmailCampaignsNewRoute,
    AuthenticatedDashboardEmailCampaignsIndexRoute:
      AuthenticatedDashboardEmailCampaignsIndexRoute,
  }

const AuthenticatedDashboardEmailCampaignsRouteWithChildren =
  AuthenticatedDashboardEmailCampaignsRoute._addFileChildren(
    AuthenticatedDashboardEmailCampaignsRouteChildren,
  )

interface AuthenticatedDashboardEmailRouteChildren {
  AuthenticatedDashboardEmailAutomationsRoute: typeof AuthenticatedDashboardEmailAutomationsRouteWithChildren
  AuthenticatedDashboardEmailCampaignsRoute: typeof AuthenticatedDashboardEmailCampaignsRouteWithChildren
}

const AuthenticatedDashboardEmailRouteChildren: AuthenticatedDashboardEmailRouteChildren =
  {
    AuthenticatedDashboardEmailAutomationsRoute:
      AuthenticatedDashboardEmailAutomationsRouteWithChildren,
    AuthenticatedDashboardEmailCampaignsRoute:
      AuthenticatedDashboardEmailCampaignsRouteWithChildren,
  }

const AuthenticatedDashboardEmailRouteWithChildren =
  AuthenticatedDashboardEmailRoute._addFileChildren(
    AuthenticatedDashboardEmailRouteChildren,
  )

interface AuthenticatedDashboardEmailsRouteChildren {
  AuthenticatedDashboardEmailsBusinessIdRoute: typeof AuthenticatedDashboardEmailsBusinessIdRoute
}

const AuthenticatedDashboardEmailsRouteChildren: AuthenticatedDashboardEmailsRouteChildren =
  {
    AuthenticatedDashboardEmailsBusinessIdRoute:
      AuthenticatedDashboardEmailsBusinessIdRoute,
  }

const AuthenticatedDashboardEmailsRouteWithChildren =
  AuthenticatedDashboardEmailsRoute._addFileChildren(
    AuthenticatedDashboardEmailsRouteChildren,
  )

interface AuthenticatedDashboardImagesRouteChildren {
  AuthenticatedDashboardImagesBusinessIdRoute: typeof AuthenticatedDashboardImagesBusinessIdRoute
}

const AuthenticatedDashboardImagesRouteChildren: AuthenticatedDashboardImagesRouteChildren =
  {
    AuthenticatedDashboardImagesBusinessIdRoute:
      AuthenticatedDashboardImagesBusinessIdRoute,
  }

const AuthenticatedDashboardImagesRouteWithChildren =
  AuthenticatedDashboardImagesRoute._addFileChildren(
    AuthenticatedDashboardImagesRouteChildren,
  )

interface AuthenticatedDashboardPostsRouteChildren {
  AuthenticatedDashboardPostsBusinessIdRoute: typeof AuthenticatedDashboardPostsBusinessIdRoute
}

const AuthenticatedDashboardPostsRouteChildren: AuthenticatedDashboardPostsRouteChildren =
  {
    AuthenticatedDashboardPostsBusinessIdRoute:
      AuthenticatedDashboardPostsBusinessIdRoute,
  }

const AuthenticatedDashboardPostsRouteWithChildren =
  AuthenticatedDashboardPostsRoute._addFileChildren(
    AuthenticatedDashboardPostsRouteChildren,
  )

interface AuthenticatedDashboardProductsRouteChildren {
  AuthenticatedDashboardProductsProductIdRoute: typeof AuthenticatedDashboardProductsProductIdRoute
  AuthenticatedDashboardProductsNewRoute: typeof AuthenticatedDashboardProductsNewRoute
  AuthenticatedDashboardProductsIndexRoute: typeof AuthenticatedDashboardProductsIndexRoute
}

const AuthenticatedDashboardProductsRouteChildren: AuthenticatedDashboardProductsRouteChildren =
  {
    AuthenticatedDashboardProductsProductIdRoute:
      AuthenticatedDashboardProductsProductIdRoute,
    AuthenticatedDashboardProductsNewRoute:
      AuthenticatedDashboardProductsNewRoute,
    AuthenticatedDashboardProductsIndexRoute:
      AuthenticatedDashboardProductsIndexRoute,
  }

const AuthenticatedDashboardProductsRouteWithChildren =
  AuthenticatedDashboardProductsRoute._addFileChildren(
    AuthenticatedDashboardProductsRouteChildren,
  )

interface AuthenticatedDashboardStorefrontRouteChildren {
  AuthenticatedDashboardStorefrontBusinessIdRoute: typeof AuthenticatedDashboardStorefrontBusinessIdRoute
}

const AuthenticatedDashboardStorefrontRouteChildren: AuthenticatedDashboardStorefrontRouteChildren =
  {
    AuthenticatedDashboardStorefrontBusinessIdRoute:
      AuthenticatedDashboardStorefrontBusinessIdRoute,
  }

const AuthenticatedDashboardStorefrontRouteWithChildren =
  AuthenticatedDashboardStorefrontRoute._addFileChildren(
    AuthenticatedDashboardStorefrontRouteChildren,
  )

interface AuthenticatedDashboardUgcRouteChildren {
  AuthenticatedDashboardUgcBusinessIdRoute: typeof AuthenticatedDashboardUgcBusinessIdRoute
}

const AuthenticatedDashboardUgcRouteChildren: AuthenticatedDashboardUgcRouteChildren =
  {
    AuthenticatedDashboardUgcBusinessIdRoute:
      AuthenticatedDashboardUgcBusinessIdRoute,
  }

const AuthenticatedDashboardUgcRouteWithChildren =
  AuthenticatedDashboardUgcRoute._addFileChildren(
    AuthenticatedDashboardUgcRouteChildren,
  )

interface AuthenticatedDashboardVideosRouteChildren {
  AuthenticatedDashboardVideosBusinessIdRoute: typeof AuthenticatedDashboardVideosBusinessIdRoute
}

const AuthenticatedDashboardVideosRouteChildren: AuthenticatedDashboardVideosRouteChildren =
  {
    AuthenticatedDashboardVideosBusinessIdRoute:
      AuthenticatedDashboardVideosBusinessIdRoute,
  }

const AuthenticatedDashboardVideosRouteWithChildren =
  AuthenticatedDashboardVideosRoute._addFileChildren(
    AuthenticatedDashboardVideosRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdsRoute: typeof AuthenticatedDashboardAdsRouteWithChildren
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRouteWithChildren
  AuthenticatedDashboardAutomationsRoute: typeof AuthenticatedDashboardAutomationsRouteWithChildren
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardContactsRoute: typeof AuthenticatedDashboardContactsRouteWithChildren
  AuthenticatedDashboardContentRoute: typeof AuthenticatedDashboardContentRouteWithChildren
  AuthenticatedDashboardEarningsRoute: typeof AuthenticatedDashboardEarningsRoute
  AuthenticatedDashboardEmailRoute: typeof AuthenticatedDashboardEmailRouteWithChildren
  AuthenticatedDashboardEmailsRoute: typeof AuthenticatedDashboardEmailsRouteWithChildren
  AuthenticatedDashboardImagesRoute: typeof AuthenticatedDashboardImagesRouteWithChildren
  AuthenticatedDashboardNewRoute: typeof AuthenticatedDashboardNewRoute
  AuthenticatedDashboardPaymentLinksRoute: typeof AuthenticatedDashboardPaymentLinksRoute
  AuthenticatedDashboardPayoutsRoute: typeof AuthenticatedDashboardPayoutsRoute
  AuthenticatedDashboardPostsRoute: typeof AuthenticatedDashboardPostsRouteWithChildren
  AuthenticatedDashboardProductsRoute: typeof AuthenticatedDashboardProductsRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardStorefrontRoute: typeof AuthenticatedDashboardStorefrontRouteWithChildren
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardUgcRoute: typeof AuthenticatedDashboardUgcRouteWithChildren
  AuthenticatedDashboardVideosRoute: typeof AuthenticatedDashboardVideosRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardIntegrationsMetaRoute: typeof AuthenticatedDashboardIntegrationsMetaRoute
  AuthenticatedDashboardIntegrationsPixelsRoute: typeof AuthenticatedDashboardIntegrationsPixelsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdsRoute: AuthenticatedDashboardAdsRouteWithChildren,
    AuthenticatedDashboardAnalyticsRoute:
      AuthenticatedDashboardAnalyticsRouteWithChildren,
    AuthenticatedDashboardAutomationsRoute:
      AuthenticatedDashboardAutomationsRouteWithChildren,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardContactsRoute:
      AuthenticatedDashboardContactsRouteWithChildren,
    AuthenticatedDashboardContentRoute:
      AuthenticatedDashboardContentRouteWithChildren,
    AuthenticatedDashboardEarningsRoute: AuthenticatedDashboardEarningsRoute,
    AuthenticatedDashboardEmailRoute:
      AuthenticatedDashboardEmailRouteWithChildren,
    AuthenticatedDashboardEmailsRoute:
      AuthenticatedDashboardEmailsRouteWithChildren,
    AuthenticatedDashboardImagesRoute:
      AuthenticatedDashboardImagesRouteWithChildren,
    AuthenticatedDashboardNewRoute: AuthenticatedDashboardNewRoute,
    AuthenticatedDashboardPaymentLinksRoute:
      AuthenticatedDashboardPaymentLinksRoute,
    AuthenticatedDashboardPayoutsRoute: AuthenticatedDashboardPayoutsRoute,
    AuthenticatedDashboardPostsRoute:
      AuthenticatedDashboardPostsRouteWithChildren,
    AuthenticatedDashboardProductsRoute:
      AuthenticatedDashboardProductsRouteWithChildren,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardStorefrontRoute:
      AuthenticatedDashboardStorefrontRouteWithChildren,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardUgcRoute: AuthenticatedDashboardUgcRouteWithChildren,
    AuthenticatedDashboardVideosRoute:
      AuthenticatedDashboardVideosRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardIntegrationsMetaRoute:
      AuthenticatedDashboardIntegrationsMetaRoute,
    AuthenticatedDashboardIntegrationsPixelsRoute:
      AuthenticatedDashboardIntegrationsPixelsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PayCodeRoute: PayCodeRoute,
  SSlugRoute: SSlugRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
