// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

async function resolveSupabaseAuthContext() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Response(message, { status: 500 });
  }
  
  const { getRequest } = await import('@tanstack/react-start/server');
  const request = getRequest();

  if (!request?.headers) {
    throw new Response('Unauthorized: No request headers available', { status: 401 });
  }

  const authHeader = request.headers.get('authorization');

  if (!authHeader) {
    throw new Response('Unauthorized: No authorization header provided', { status: 401 });
  }

  if (!authHeader.startsWith('Bearer ')) {
    throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
  }

  const token = authHeader.replace('Bearer ', '');
  if (!token) {
    throw new Response('Unauthorized: No token provided', { status: 401 });
  }

  const supabase = createClient<Database>(
    SUPABASE_URL!,
    SUPABASE_PUBLISHABLE_KEY!,
    {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    }
  );

  const { data, error } = await supabase.auth.getClaims(token);
  if (error || !data?.claims) {
    throw new Response('Unauthorized: Invalid token', { status: 401 });
  }

  if (!data.claims.sub) {
    throw new Response('Unauthorized: No user ID found in token', { status: 401 });
  }

  return {
    supabase,
    userId: data.claims.sub,
    claims: data.claims,
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const authContext = await resolveSupabaseAuthContext();

    return next({
      context: authContext,
    })
  }
)

export const optionalSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    try {
      const authContext = await resolveSupabaseAuthContext();
      return (next as any)({ context: { ...authContext, authError: null } });
    } catch (error) {
      console.warn('[Supabase] Optional auth unavailable', error);
      return (next as any)({
        context: {
          supabase: null,
          userId: null,
          claims: null,
          authError: error,
        },
      });
    }
  }
)
